#!/bin/bash

apt-get update
apt-get -y install software-properties-common
add-apt-repository -y ppa:staticfloat/juliareleases     
add-apt-repository -y ppa:staticfloat/julia-deps     

apt-get update
apt-get -y upgrade

apt-get -y install julia pandoc ipython ipython-notebook nettle-dev sudo


addgroup --gid 1000 user
adduser --system --home /data --no-create-home --uid 1000 --group user

mkdir -p /data/notebooks
chown user:user -R /data 
cd /data

sudo -H -u user julia -e "Pkg.add(\"IJulia\")"
sudo -H -u user julia -e "Pkg.add(\"Gadfly\")"


